language: python
services:
  - postgresql
python:
  - 3.6
install:
  - pip install -r app/requirements.txt
before_script:
  - python app/manage.py migrate
  - python app/manage.py fill_db
script:
  - python app/manage.py test
