language: python
services:
  - postgresql
python:
  - 3.6
env:
  - DKRD_DB_HOST=127.0.0.1
install:
  - pip install -r app/requirements.txt
before_script:
  - python app/manage.py migrate
  - python app/manage.py fill_db
script:
  - python app/manage.py test
