language: python
services:
  - postgresql
python:
  - 3.6
  - 3.5
env:
  - DKRD_DB_HOST=127.0.0.1
before_install:
  - docker build -t angiriscouncil/cain .
install:
  - pip install -r app/requirements.txt
before_script:
  - python app/manage.py migrate
  - python app/manage.py fill_db
script:
  - python app/manage.py test
after_success:
  - if [ "$TRAVIS_BRANCH" != "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push angiriscouncil/cain:dev;
    fi
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push angiriscouncil/cain:master;
    fi