script:
  - docker-compose -f docker-compose.test.yml run web bash -c "deploy/wait-for-it.sh -h db -p 5432 -t 30 -- python3 app/manage.py test"
after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  - if [ "$TRAVIS_BRANCH" == "dev" ]; then docker build . -t angiriscouncil/cain:dev; docker push angiriscouncil/cain:dev; fi
  - if [ "$TRAVIS_BRANCH" == "master" ]; then docker build . -t angiriscouncil/cain:master; docker push angiriscouncil/cain:master; fi