language: python
services:
  - postgresql
env:
  - DKRD_DB_HOST=127.0.0.1
install:
  - docker build -t angiriscouncil/cain:dev .
script:
  - docker run angiriscouncil/cain:dev /bin/sh -c "cd /home/docker/code/app; python manage.py migrate; "
after_success:
  - if [ "$TRAVIS_BRANCH" != "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push angiriscouncil/cain:dev;
    fi
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push angiriscouncil/cain:master;
    fi