version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  web:
    environment:
      - DKRD_DEBUG=off
      - DKRD_ALLOWED_HOSTS=mundep.com
      - DKRD_SITE_DOMAIN=mundep.com
    image: angiriscouncil/cain:master
    volumes:
      - ./media:/home/docker/code/app/media
    ports:
      - "80:80"
    depends_on:
      - db