version: '3'

services:
  db:
    image: postgres
  web:
    environment:
      - DKRD_DEBUG=off
      - DKRD_ALLOWED_HOSTS=mundep.com
      - DKRD_SITE_DOMAIN=mundep.com
    image: angiriscouncil/cain:master
    volumes:
      - .:/home/docker/code
    ports:
      - "80:80"
    depends_on:
      - db